### ISSUE TITLE
Rectify bug that takes down the website when closing a case

### ISSUE THREAD

**Issue by caje731** [caje731/helpinghands#35]
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/104073632999288/119721850579253)
┆Attachments: <a href="https:&#x2F;&#x2F;app.asana.com&#x2F;app&#x2F;asana&#x2F;-&#x2F;download_asset?asset_id&#x3D;119721850579256">WhatsApp-Image-20160503.jpg</a>

**Comment by caje731** [comment]
Attached screenshot taken by Jivan after he closed the only active case. Stacktrace from the PA logs :

2016-04-29 19:27:14,690 :Internal Server Error: /
Traceback (most recent call last):
  File "/home/caje731/Envs/helpinghands/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/caje731/Envs/helpinghands/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, _callback_args, *_callback_kwargs)
  File "/home/caje731/Envs/helpinghands/helpinghands/donations/views.py", line 19, in home
    current_case = list(CaseDetail.objects.filter(status=3).order_by('-id'))[-1]

[--- Commented from Asana.com
#commenter Cajetan Rodrigues
---[aa]

**Comment by caje731** [comment]
caje731 pushed to branch master of caje731/helpinghands (https://github.com/caje731/helpinghands/commit/9f4f87a898ed710690c823b613b396616f3448e8)
- #119721850579253 Rectify IndexError when accessing current case

[--- Commented from Asana.com
#commenter Cajetan Rodrigues
---[aa]

**Comment by caje731** [comment]
➤ Cajetan Rodrigues commented:
caje731 pushed to branch dit of caje731/helpinghands (https://github.com/caje731/helpinghands/commit/9f4f87a898ed710690c823b613b396616f3448e8)
- #119721850579253 Rectify IndexError when accessing current case
