### ISSUE TITLE
Updating profile throws error

### ISSUE THREAD

**Issue by caje731** [caje731/helpinghands#36]
Found this in the error logs:

2016-04-30 20:50:32,279 :Internal Server Error: /accounts/profile/
Traceback (most recent call last):
  File "/home/caje731/Envs/helpinghands/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/caje731/Envs/helpinghands/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/caje731/Envs/helpinghands/local/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/caje731/Envs/helpinghands/local/lib/python2.7/site-packages/django/contrib/auth/mixins.py", line 56, in dispatch
    return super(LoginRequiredMixin, self).dispatch(request, *args, **kwargs)
  File "/home/caje731/Envs/helpinghands/local/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/caje731/Envs/helpinghands/helpinghands/donations/views.py", line 312, in patch
    if data['patch_type'] == 'address':
  File "/home/caje731/Envs/helpinghands/local/lib/python2.7/site-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'patch_type'"

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/104073632999288/119721850579260)

**Comment by caje731** [comment]
caje731 pushed to branch master of caje731/helpinghands (https://github.com/caje731/helpinghands/commit/ff8a22adf39e75215f8425594c766aa7041a74d8)
- #119721850579260 Rectify missing patch_type issue

[--- Commented from Asana.com
#commenter Cajetan Rodrigues
---[aa]

**Comment by caje731** [comment]
➤ Cajetan Rodrigues commented:
caje731 pushed to branch dit of caje731/helpinghands (https://github.com/caje731/helpinghands/commit/ff8a22adf39e75215f8425594c766aa7041a74d8)
- #119721850579260 Rectify missing patch_type issue
