### ISSUE TITLE
Fix float-value bug that affects creation of a new case

### ISSUE THREAD

**Issue by caje731** [caje731/helpinghands#38]
Trace from error log:
2016-05-04 13:51:21,913 :Internal Server Error: /cases/new/
Traceback (most recent call last):
  File "/home/caje731/Envs/helpinghands/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/caje731/Envs/helpinghands/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, _callback_args, *_callback_kwargs)
  File "/home/caje731/Envs/helpinghands/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, _args, *_kwargs)
  File "/home/caje731/Envs/helpinghands/helpinghands/donations/views.py", line 145, in create_case
    wish_amount=data['wish_amt'],
  File "/home/caje731/Envs/helpinghands/local/lib/python2.7/site-packages/django/db/models/manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(_args, *_kwargs)
  File "/home/caje731/Envs/helpinghands/local/lib/python2.7/site-packages/django/db/models/query.py", line 401, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/caje731/Envs/helpinghands/local/lib/python2.7/site-packages/django/db/models/base.py", line 700, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/caje731/Envs/helpinghands/local/lib/python2.7/site-packages/django/db/models/base.py", line 728, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/caje731/Envs/helpinghands/local/lib/python2.7/site-packages/django/db/models/base.py", line 812, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/home/caje731/Envs/helpinghands/local/lib/python2.7/site-packages/django/db/models/base.py", line 851, in _do_insert
    using=using, raw=raw)
  File "/home/caje731/Envs/helpinghands/local/lib/python2.7/site-packages/django/db/models/manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(_args, *_kwargs)
  File "/home/caje731/Envs/helpinghands/local/lib/python2.7/site-packages/django/db/models/query.py", line 1039, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/caje731/Envs/helpinghands/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 1063, in execute_sql
    for sql, params in self.as_sql():
  File "/home/caje731/Envs/helpinghands/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 1023, in as_sql
    for obj in self.query.objs
  File "/home/caje731/Envs/helpinghands/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 962, in prepare_value
    value = field.get_db_prep_save(value, connection=self.connection)
  File "/home/caje731/Envs/helpinghands/local/lib/python2.7/site-packages/django/db/models/fields/__init__.py", line 728, in get_db_prep_save
    prepared=False)
  File "/home/caje731/Envs/helpinghands/local/lib/python2.7/site-packages/django/db/models/fields/**init**.py", line 720, in get_db_prep_value
    value = self.get_prep_value(value)
  File "/home/caje731/Envs/helpinghands/local/lib/python2.7/site-packages/django/db/models/fields/**init**.py", line 1789, in get_prep_value
    return float(value)
ValueError: invalid literal for float(): 50,000

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/104073632999288/120398434388725)

**Comment by caje731** [comment]
caje731 pushed to branch master of caje731/helpinghands (https://github.com/caje731/helpinghands/commit/dfb66f77295e7305bbd673fa24980c74d75028c3)
- #120398434388725 Fix float-value input validation

[--- Commented from Asana.com
#commenter Cajetan Rodrigues
---[aa]

**Comment by caje731** [comment]
➤ Cajetan Rodrigues commented:
caje731 pushed to branch dit of caje731/helpinghands (https://github.com/caje731/helpinghands/commit/dfb66f77295e7305bbd673fa24980c74d75028c3)
- #120398434388725 Fix float-value input validation
